[model]
type = "StudentMBoardAgent"

[model.kwargs]
board_channels = 46
board_size = 10
global_dim = 0

width = 48
num_blocks = 2
global_hidden_dim = 64
value_hidden_dims = [64]
activation = "tanh"
use_global_film = false
use_global_policy_bias = false
