[model]
type = "DiscreteBoardAgent"

[model.kwargs]
model_type = "cnn_fc"
board_channels = 7
board_size = 10
global_dim = 0
cnn_channels = [64, 128, 128]
cnn_kernels = [3, 3, 3]
cnn_strides = [1, 1, 1]
cnn_paddings = [1, 1, 1]
trunk_hidden_dims = [768, 512, 256]
actor_head_hidden_dims = [256, 128]
critic_head_hidden_dims = [256, 128]
